@startuml

!theme monokai_npp from .styles
scale 1.2

class Application {
    +view: MainMenu | Game
    -is_alive() → //bool//
}

class Game {
    +pet: model.Creature
}

class CreatureLoader {
    +get_new_creature() → model.Creature
    +get_creature_from_file() → model.Creature
}

class MainMenu

class KindLoader {
    +get_kinds() → <i>list</i> [model.Kind]
}

class FileIO {
    +{static}data_path: <i>Path</i>
    +get_kind_files()
}

hide class empty members

Application o-- MainMenu
Application o-- Game

MainMenu ..> KindLoader

KindLoader .right.> FileIO

Game ..> CreatureLoader

@enduml
