@startuml

!theme monokai_npp from .styles
scale 1.2

legend bottom left
    //~# переменные аннотаций//
    TypeCrParam = Type[CreatureParameter]
    KParamsDict = dict[TypeCrParam, KindParameter]
    CrParamsDict = dict[TypeCrParam, CreatureParameter]
end legend

interface dict

interface DictOfRanges {
    <font:Brass Mono><size:12>(int, int): Any
    --
    __init__()
    __getitem__()
}

class Kind {
    <font:Brass Mono><size:12>(int, int): MatureStage
    --
    +file_name: <i>str</i>
    +str_name: <i>str</i>
}

class MatureStage {
    +days: <i>int</i>
    +params: <font:Noto Mono><size:14>KParamsDict
}

abstract Parameter {
    -min: <i>float</i>
    -max: <i>float</i>
    -delta: <i>float</i>
}

class KindParameter << dataclass >> {
    +default: <i>float</i>
}

class Creature {
    +kind: Kind
    #age: <i>int</i>
    +params: <font:Noto Mono><size:14>CrParamsDict
    --<size:12>// getters  // --
    +age → <i>int</i>
    --<size:12>// setters  // --
    +age()
    --<size:12>// methods  // --
    -grow_up()
}

abstract CreatureParameter {
    +{static}name: <i>str</i>
    #value: <i>float</i>
    --<size:12>// getters  // --
    +range → <i>tuple</i> [<i>float</i> , <i>float</i> ]
    +value → <i>float</i>
    --<size:12>// setters  // --
    +value()
    --<size:12>// methods  // --
    +{abstract}update()
}

class Health {
    +update()
}

class Satiety {
    +update()
}

class Emotion {
    +update()
}

hide abstract empty members
hide class empty members
hide interface empty members

left to right direction

dict <|- DictOfRanges

DictOfRanges <|- Kind

Kind o- MatureStage

Parameter <|- KindParameter
Parameter <|-- CreatureParameter

MatureStage o-- KindParameter

Creature o-up- Kind
Creature o-- CreatureParameter

CreatureParameter <|-- Health
CreatureParameter <|-- Satiety
CreatureParameter <|-- Emotion

@enduml
